# This is a basic workflow to help you get started with Actions

name: pull-request-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-job:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: pwd | ls

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: '5.x'
     
      - name: Restore NuGet Packages
        run: nuget restore .\WPF\Cloud77.WPF.sln

      - name: Build and Publish Web App
        run: msbuild .\WPF\Cloud77.WPF.sln /p:Configuration=Release /p:Platform=x64

      - name: Download squirrel and releases.zip
        run: .\download.ps1

        # nuget pack
      - name: Pack
        run: nuget pack Cloud77.WPF.stable.nuspec -Version 1.0.0 -OutputDirectory .\nupkg -Properties Configuration=Release

        # squirrel
      - name: Release
        run: .\package.ps1 -version 1.0.0 -package Cloud77

      - name: Check zip
        run: ls -Filter *.zip

      - name: Check exe
        run: ls .\releases
